version: '3'
services:
  spark-master:
    image: fcjbispo/spark-master:3.4.1-hadoop3.3
    container_name: fbnet-spark-master
    hostname: spark-master
    networks:
      - fbnet-hadoop
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=true

  spark-worker1:
    image: fcjbispo/spark-worker:3.4.1-hadoop3.3
    container_name: fbnet-spark-worker1
    hostname: spark-worker1
    networks:
      - fbnet-hadoop
    restart: unless-stopped
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker2:
    image: fcjbispo/spark-worker:3.4.1-hadoop3.3
    container_name: fbnet-spark-worker2
    hostname: spark-worker2
    networks:
      - fbnet-hadoop
    restart: unless-stopped
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-history-server:
    image: fcjbispo/spark-historyserver:3.4.1-hadoop3.3
    container_name: fbnet-spark-historyserver
    networks:
      - fbnet-hadoop
    restart: always
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - spark_historyserver:/tmp/spark-events

volumes:
  spark_historyserver:
    name: vol-spark_historyserver
    driver: local
    driver_opts:
      o: bind
      type: none
      device: F:\FBNet\spark-cluster-historyserver

networks:
  fbnet-hadoop:
    driver: bridge
    external: True